### ISSUE TITLE
WDA not accessible on http://localhost:8100

### ISSUE THREAD

**Issue by EitanBe** [tmobile/stf_ios_support#21]
I can see the device in the dashboard in disconnected state.
Not ather issue except: 

./view_log -proc stf_device_ios

2020-02-20T07:24:13.481Z ERR/device-ios:plugins:wdaCommands 79501 [UUID] Session renew "http://localhost:8100/status" failed FetchError: request to http://localhost:8100/status failed, reason: connect ECONNREFUSED 127.0.0.1:8100
    at ClientRequest.<anonymous> (/Users/<User>/stam/stf_ios_support/repos/stf-ios-provider/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:321:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Environment: 
git pull the latest code srf-ios-provider
and run npm install
pull the latest in stf-ios-supprt
run ./init.sh

**Comment by EitanBe** [comment]
2020-02-23T13:32:08.150Z ERR/device-ios:plugins:wdaCommands 1619 [UDID] Session renew "http://localhost:8100/status" failed FetchError: request to http://localhost:8100/status failed, reason: connect ECONNREFUSED 127.0.0.1:8100
    at ClientRequest.<anonymous> (/Users/<User>/stam/stf_ios_support/repos/stf-ios-provider/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:321:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-02-23T13:32:38.147Z ERR/device-ios:plugins:wdaCommands 1619 [UDID] Session renew "http://localhost:8100/status" failed FetchError: request to http://localhost:8100/status failed, reason: connect ECONNREFUSED 127.0.0.1:8100
    at ClientRequest.<anonymous> (/Users/<User>/stam/stf_ios_support/repos/stf-ios-provider/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:321:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by nanoscopic** [comment]
When wdaproxy is running, which in turn starts wda, http://localhost:8100 will be accessible within a browser on the same machine. You can look at the logs of wdaproxy, wda, and wda wrapper plist:

`./view_log -proc wdaproxy`
`./view_log -proc wda`
`cat logs/wda_wrapper_stderr`
`cat logs/wda_wrapper_stdout`

**Comment by Bull3time** [comment]
I had this but I found i had to hardcode my fullpath to the wda directory throughout wdaproxy and coordinator (maybe even wda_wrapper) cant remember now. There were multiple places where wdaDir or whatever it was were hardcoded. 

Should note im running it via ./run as the app building didnt work so unsure if thats messed with the path, either way it was annoying having to go through and find all the hardcoded references.

**Comment by nanoscopic** [comment]
The path used for the wda directory can be configured in config.json via wda_folder ( eg: https://github.com/tmobile/stf_ios_support/blob/master/config.json.example#L26 )

If you have issues with the relative path, you can set the path to some full path there. There generally shouldn't be / aren't any more hardcoded paths within the setup.

So long as the current working directory you are in when you do `./run` contains `./bin/wda` folder, then the relative path will work. If there is some way to demonstrate it not working I'd be happy to diagnose what is going on and fix it. I haven't had any problem with the relative paths on any of the 30+ machines I've set it up on so far. ( mac minis, macbook pros, etc )

**Comment by nanoscopic** [comment]
My understanding is that this was a failure of the whole setup to build completely. I know of no issues with stf_ios_support currently that cause the errors above. If a set of steps in a fresh clone of the repo can be taken that allow me to reproduce the issue I'll be happy to investigate further. If that can be done reopen the ticket. Otherwise I'm assuming this issue has been solved.
