### ISSUE TITLE
random mismash of issues

### ISSUE THREAD

**Issue by tepmehatop** [tmobile/stf_ios_support#24]
Hi, have a problems with make :( hope for any help....
@nanoscopic pleaseeeee.....

**Step by step** 

1. after success  build WebDriverAgent i get 

```
/Users/imac/Library/Developer/Xcode/DerivedData/WebDriverAgent-boqgdipwyemgxvbxmrkrkjvgpbzh/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app: replacing existing signature

** TEST BUILD SUCCEEDED **

FAIL TO GET PRODUCTION PATH - you should rerun make
make: *** [bin/wda/build_info.json] Error 1

```

2. Rerun make
```
iMac-IMac:stf_ios_support-master imac$ make
cd repos/WebDriverAgent && ./Scripts/bootstrap.sh
Fetching dependencies
Dependencies up-to-date
ln -s ../../repos/wdaproxy/web bin/wda/web
.............................................
.............................................
.............................................
** TEST BUILD SUCCEEDED **

git clone https://github.com/nanoscopic/ffmpeg.git repos/ffmpeg
Cloning into 'repos/ffmpeg'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 507342 (delta 0), reused 1 (delta 0), pack-reused 507339
Receiving objects: 100% (507342/507342), 125.30 MiB | 1.82 MiB/s, done.
Resolving deltas: 100% (401839/401839), done.
Checking out files: 100% (7124/7124), done.
cd repos/ffmpeg && ./configure  --prefix=/usr/local --enable-gpl --enable-nonfree --enable-libx264 --enable-libx265 --enable-libxvid
install prefix            /usr/local
source path               .
C compiler                gcc
C library                 
ARCH                      x86 (generic)
big-endian                no
runtime cpu detection     yes
standalone assembly       yes
x86 assembler             yasm
MMX enabled               yes
MMXEXT enabled            yes
3DNow! enabled            yes
.............................................
.............................................
.............................................

```

3. Stack on another error
```
.............................................
.............................................
.............................................
	vendor/github.com/codeskyblue/muuid/vendor/github.com/satori/go.uuid/README.md
	vendor/github.com/codeskyblue/muuid/vendor/github.com/satori/go.uuid/uuid.go
	vendor/github.com/codeskyblue/muuid/vendor/github.com/stretchr/testify/LICENCE.txt
	vendor/github.com/codeskyblue/muuid/vendor/github.com/stretchr/testify/LICENSE
	vendor/github.com/codeskyblue/muuid/vendor/github.com/stretchr/testify/assert/assertion_forward.go
	vendor/github.com/codeskyblue/muuid/vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
	vendor/github.com/codeskyblue/muuid/vendor/github.com/stretchr/testify/assert/assertions.go
	vendor/github.com/codeskyblue/muuid/vendor/github.com/stretchr/test
Aborting
package github.com/openatx/wdaproxy/connector: exit status 1
# cd /Users/imac/go/src/github.com/shurcooL/vfsgen; git pull --ff-only
From https://github.com/shurcooL/vfsgen
 * branch            HEAD       -> FETCH_HEAD
error: The following untracked working tree files would be overwritten by merge:
	.travis.yml
	CONTRIBUTING.md
	LICENSE
	README.md
	cmd/vfsgendev/generate.go
	cmd/vfsgendev/main.go
	cmd/vfsgendev/parse.go
	commentwriter.go
	doc.go
	generator.go
	generator_test.go
	options.go
	stringwriter.go
	test/doc.go
	test/test_gen.go
	test/test_test.go
	test/test_vfsdata_test.go
Please move or remove them before you merge.
Aborting
package github.com/shurcooL/vfsgen: exit status 1
# cd /Users/imac/go/src/github.com/sirupsen/logrus; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package github.com/sirupsen/logrus: exit status 1

```

4. rerun make and get another error
```

iMac-IMac:stf_ios_support-master imac$ make
cd repos/WebDriverAgent && ./Scripts/bootstrap.sh
Fetching dependencies
Dependencies up-to-date
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C repos/wdaproxy
go get . & exit 0
go get ./... & exit 0
go build .
go get: no install location for directory /Users/imac/Desktop/iosSTF/stf_ios_support-master/repos/wdaproxy outside GOPATH
	For more details see: 'go help gopath'
go get: no install location for directory /Users/imac/Desktop/iosSTF/stf_ios_support-master/repos/wdaproxy outside GOPATH
	For more details see: 'go help gopath'
cd bin &&	ln -s ../repos/wdaproxy/wdaproxy wdaproxy
go get github.com/fsnotify/fsnotify
go get github.com/sirupsen/logrus
go build view_log.go
make: *** No rule to make target `coordinator/icon/stf.icns', needed by `icns'.  Stop.


```
5. Ok here problem is not found the icon "stf.icns" , ok created it manually 

6. rerun make and get another error
```

iMac-IMac:stf_ios_support-master imac$ make
cd repos/WebDriverAgent && ./Scripts/bootstrap.sh
Fetching dependencies
Dependencies up-to-date
mkdir -p STF\ Coordinator.app/Contents/MacOS
mkdir -p STF\ Coordinator.app/Contents/Resources
cp coordinator/icon/stf.icns STF\ Coordinator.app/Contents/Resources/icon.icns
cp bin/coordinator STF\ Coordinator.app/Contents/MacOS/
echo '{"config_path":"/Users/imac/Desktop/iosSTF/stf_ios_support-master/config.json"}' > STF\ Coordinator.app/Contents/Resources/config.json
cp coordinator/app/Info.plist STF\ Coordinator.app/Contents/
./get-version-info.sh ios_support > STF\ Coordinator.app/Contents/Resources/build_info.json
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "./get-version-info.sh", line 54, in <module>
    "ios_support": git_info( '.', '.' ),
  File "./get-version-info.sh", line 11, in git_info
    remote = subprocess.check_output( ["/usr/bin/git", "remote","-v"] )
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/git', 'remote', '-v']' returned non-zero exit status 128
make: *** [STF Coordinator.app] Error 1

```

7. rerun again, and i see the double link for **stf ios provider**, the same problem was before with 
**WebDriverAgent**, i deleted in `config.json` the repos link, and problem is gone, but with  **stf ios provider** not help....

> git clone https://github.com/nanoscopic/stf-ios-provider.githttps://github.com/nanoscopic/stf-ios-provider.git

```
Mac-IMac:stf_ios_support-master imac$ make
cd repos/WebDriverAgent && ./Scripts/bootstrap.sh
Fetching dependencies
Dependencies up-to-date
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C wda_wrapper
go get
go get .
go build  -o ../bin/wda_wrapper .
git clone https://github.com/nanoscopic/stf-ios-provider.githttps://github.com/nanoscopic/stf-ios-provider.git repos/stf-ios-provider --branch master
Cloning into 'repos/stf-ios-provider'...
remote: Not Found
fatal: repository 'https://github.com/nanoscopic/stf-ios-provider.githttps://github.com/nanoscopic/stf-ios-provider.git/' not found
make: *** [repos/stf-ios-provider] Error 128

```

8. ok, git clone manually with correct link, again stack, first problem is need to update the **node**

```

iMac-IMac:stf_ios_support-master imac$ git clone https://github.com/nanoscopic/stf-ios-provider.git repos/stf-ios-provider --branch master
Cloning into 'repos/stf-ios-provider'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 132 (delta 29), reused 120 (delta 21), pack-reused 0
Receiving objects: 100% (132/132), 73.41 KiB | 647.00 KiB/s, done.
Resolving deltas: 100% (29/29), done.
iMac-IMac:stf_ios_support-master imac$ make
cd repos/WebDriverAgent && ./Scripts/bootstrap.sh
Fetching dependencies
Dependencies up-to-date
cd repos/stf-ios-provider && PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/node\@12/bin npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> zeromq@6.0.0-beta.6 install /Users/imac/Desktop/iosSTF/stf_ios_support-master/repos/stf-ios-provider/node_modules/zeromq
> node-gyp-build

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for semver@7.1.3: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.7"})
npm WARN notsup Not compatible with your version of node/npm: semver@7.1.3
npm WARN notsup Unsupported engine for zeromq@6.0.0-beta.6: wanted: {"node":">= 10.2"} (current: {"node":"8.17.0","npm":"6.13.7"})
npm WARN notsup Not compatible with your version of node/npm: zeromq@6.0.0-beta.6

added 129 packages from 108 contributors and audited 195 packages in 8.48s

3 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```

9. ok update the node 
```
iMac-IMac:stf-ios-provider imac$ sudo n stable
iMac-IMac:stf-ios-provider imac$ npm update -g
iMac-IMac:stf-ios-provider imac$ node -v
v12.16.1
```

10. rerun make not helps
```

iMac-IMac:stf_ios_support-master imac$ make
cd repos/WebDriverAgent && ./Scripts/bootstrap.sh
Fetching dependencies
Dependencies up-to-date

```

11 
```

iMac-IMac:stf-ios-provider imac$ npm audit fix
up to date in 0.456s

3 packages are looking for funding
  run `npm fund` for details

fixed 0 of 3 vulnerabilities in 195 scanned packages
  3 vulnerabilities required manual review and could not be updated

```
```

iMac-IMac:stf-ios-provider imac$ npm fund
stf-ios-provider@3.4.0
├─┬ ansi-styles@4.2.1
│ └── url: https://github.com/chalk/ansi-styles?sponsor=1
├─┬ glob@7.1.6
│ └── url: https://github.com/sponsors/isaacs
└─┬ p-limit@2.2.2
  └── url: https://github.com/sponsors/sindresorhus


```

12 try to install npm
```

iMac-IMac:stf_ios_support-master imac$ cd repos/stf-ios-provider && PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/node\@12/bin npm install
audited 195 packages in 1.137s

3 packages are looking for funding
  run `npm fund` for details

found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```

13. get for example **ansi-styles** manually and get more **34 packages are looking for funding** 
```

iMac-IMac:stf-ios-provider imac$ npm fund
stf-ios-provider@3.4.0
└─┬ ansi-styles@4.2.1
  ├── url: https://github.com/chalk/ansi-styles?sponsor=1
  ├─┬ @babel/core@7.8.4
  │ ├── type: opencollective
  │ └── url: https://opencollective.com/babel
  ├─┬ cli-truncate@2.1.0, figures@3.2.0, get-port@5.1.1, make-dir@3.0.2, pretty-ms@5.1.0, p-limit@2.2.2, is-finite@1.1.0, read-pkg-up@7.0.1
  │ └── url: https://github.com/sponsors/sindresorhus
  ├─┬ has-symbols@1.0.1, resolve@1.15.1, is-date-object@1.0.2, is-regex@1.0.5, object-is@1.0.2, is-symbol@1.0.3, es-to-primitive@1.2.1, is-callable@1.1.5, object-inspect@1.7.0, string.prototype.trimleft@2.1.1, string.prototype.trimright@2.1.1, es-abstract@1.17.4, regexp.prototype.flags@1.3.0, deep-equal@1.1.1, object.values@1.1.1, object.getownpropertydescriptors@2.1.0, util.promisify@1.0.1, is-string@1.0.5, array-includes@3.1.1, array.prototype.flat@1.2.3
  │ └── url: https://github.com/sponsors/ljharb
  ├─┬ picomatch@2.2.1
  │ └── url: https://github.com/sponsors/jonschlinkert
  ├─┬ glob@7.1.6
  │ └── url: https://github.com/sponsors/isaacs
  ├─┬ eslint@6.8.0
  │ └── url: https://opencollective.com/eslint
  └─┬ find-cache-dir@3.3.0
    └── url: https://github.com/avajs/find-cache-dir?sponsor=1

```

14. if i do run, i get another fatal error.....
```

iMac-IMac:stf_ios_support-master imac$ ./run
\FATA[0000] 2 invalid character '{' after top-level value 


```

config,json i checked via validator
help please, stuck with to problems.... 

 3 packages are looking for funding  and    \FATA[0000] 2 invalid character '{' after top-level value

@nanoscopic very very hope for any help, thank's a lot!

**Comment by nanoscopic** [comment]
There are too many different issues here to keep track of in a single ticket but I will address the issues I see and understand as best as possible.

First of all, the "coordinator/icon" issues that prevent the app from building are now fixed. They were due to an incomplete set of changes moving all the icon files into a subdirectory.

Second, the "FAIL TO GET PRODUCTION PATH - you should rerun make" is known and the message intentional as it always happens the first time around. I'm not sure the cause and rerunning make always fixes that specific error.

Third, the wdaproxy error messages are due to dependencies not being fetched correctly on initial clean clone and running of make. I tried this out this morning and got similar errors. Rerunning make it appeared to work okay. If in doubt, you can `cd repos/wdaproxy` then `make clean` there, then `make`; to ensure wdaproxy is definitely built correctly.

Fourth, the vulnerabilities are due to outdated dependencies in the upstream stf-syrup package. You should report those to upstream openstf project to get them resolved.

Fifth, the current stf-ios-provider has been updated to work with node@12 and is essentially hardcoded right now to use node 12. While I believe it works also with older node, an it worked with node 8 once in my testing, I wouldn't recommend it.

Sixth, the "invalid character" stuff spit out is generally due to copy / pasting "//" comment lines into config.json. JSON doesn't allow those; I only added them to explain what the various example blocks look like. Remove the comment line and it should parse. I have just pushed an update the explains this more clearly in the example json config file. If in doubt, run `python -m json.tool config.json` to see if your config.json can be parsed by python. If not, fix it.

Seventh, you'll need to explain more about `npm fund`. Is there some reason it is important here?

Eighth, signing was specified when it wasn't needed on both video_enabler, and on repos/osx_ios_device_trigger. That has been corrected. You'll need to pull repos/osx_ios_device_trigger.

In summary: Fix your config.json so it is parseable first. Until it is correct `make` will break in all sorts of ways.

**Comment by nanoscopic** [comment]
Hopefully the information above and the recent commits resolve the majority of the issues above. If not please create individual tickets with each particular error / issue. I can't grok having 8+ issues in a single issue, it is too confusing for me. Closing due to this.

**Comment by asmiou** [comment]
Hey hi, sorry i know this topic is old, but i got the same error message.
When I run the make command in ```/repos/wdaproxy```  as you indicated @nanoscopic . I have this error there:
```
go: github.com/DHowett/go-plist@v0.0.0-20170330020707-795cf23fd27f: missing go.sum entry; to add it:
	go mod download github.com/DHowett/go-plist
make[1]: *** [wdaproxy] Error 1
make: *** [repos/wdaproxy/wdaproxy] Error 2
```

Help please.

**Comment by nanoscopic** [comment]
As far as I'm concerned, stf_ios_support repo is deprecated. I won't be dedicating any time to supporting it. You should go look at / use github.com/nanoscopic/controlfloor and github.com/nanoscopic/ios_remote_provider. The provider is the "next generation version" of stf_ios_support.

As for the error message you show, I'm pretty sure that if you follow the advice the error gives you that error will go away. That is, run `go mod download github.com/DHowett/go-plist`.
